version: '1.0'
services:
  vulmanager-back:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app            
      - /app/node_modules  
    command: npm run start  
